#!/bin/bash

# Symlink all dotfiles into home dir

for dir in ./*
do
  [ -f "$dir" ] &&  continue
  [ ! -f "${dir}/install" ] && echo "Install ${dir} disabled" && continue
  /bin/bash $dir/install
done

