#!/bin/bash
# Insall vim configs
# Install package manager


if [ ! -d ~/.tmux/plugins/tpm ]; then 
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

ln -sf $PWD/tmux/tmux.conf $HOME/.tmux.conf
